services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: cashly-ai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cashly_ai
      POSTGRES_PASSWORD: qwerT12321
      POSTGRES_DB: cashly_ai_vectors
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    command: [ "postgres", "-c", "listen_addresses=*" ]
    volumes:
      - postgres_vector_data:/var/lib/postgresql/data
      #- ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cashly_ai -d cashly_ai_vectors" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_vector_data:
    driver: local
